language: android
# Setting java 1.8 
jdk:
  - oraclejdk8
sudo: false
env:
  global:
# Initiating clean Gradle output
    - TERM=dumb
# Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "NjcffFHd3rrH6e2S1NwUNQORM2vs2uzhBHu+22g+sXc+PeFmlWeh7tFK8fnERxRNuVcYF0Amhwu/ZSDKGAm+882p8lNiVwhw22EybxRcE/JJbsJpjdVg2fd0mzbLOc1DX+ryPoGcQaCqyhM/V0tZrtHhRvqWsM75HRmR0XSp/Sc="
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
after_script:
  - cat /home/travis/build/Countly/countly-sdk-android/sdk-messaging/build/outputs/lint-results-debug.xml
  - cat /home/travis/build/Countly/countly-sdk-android/sdk/build/reports/androidTests/connected/index.html
notifications:
addons:
